name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libcunit1 libcunit1-dev
    - name: Build string tests
      run: ./test/run_tests.sh string build
    - name: Run string tests
      run: ./test/run_tests.sh string run
    - name: Clean string tests
      run: ./test/run_tests.sh string clean
    - name: Build list tests
      run: ./test/run_tests.sh list build
    - name: Run list tests
      run: ./test/run_tests.sh list run
    - name: Clean list tests
      run: ./test/run_tests.sh list clean
